[package]
name = "snake_ctrl"
version = "0.1.0"
authors = ["mz <emgyrz@gmail.com>"]
edition = "2018"


[lib]
crate_type = [ "staticlib", "cdylib", "rlib" ]


[dependencies]
thiserror = "1.0.20"
rand = "0.7.3"